carts/urls.py
from django.contrib import admin
from django.urls import path

from .views import cart_home, cart_update, cart_checkout, checkout_success

urlpatterns = [
    path('', cart_home, name='home'),
    path('checkout/', cart_checkout, name='checkout'),
    path('checkout/success', checkout_success, name='success'),
    path('update/', cart_update, name='update'),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from django.views.generic import TemplateView, RedirectView

from accounts.views import LoginView, RegisterView, guest_register_view, AccountHomeView
from addresses.views import shipping_address_create, shipping_address_reuse
from billing.views import billing_payment_view, billing_payment_create_view
from carts.views import cart_home, cart_detais_api_view
from marketing.views import MarketingPreferenceUpdateView
from products.views import UserProductHistoryView
from .views import home_page, about_page, contact_page

urlpatterns = [
	path('', home_page, name='home'),
	path('about/', about_page, name='about'),
    path('account/', AccountHomeView.as_view(), name='accounts'),
    path('accounts/', RedirectView.as_view(url='/account')),
    path('accounts/', include("accounts.passwords.urls")),
    path('admin/', admin.site.urls),
    path('api/cart/', cart_detais_api_view, name='api_cart'),
    path('billing-payment/', billing_payment_view, name='billing-payment'),
    path('billing-payment/create/', billing_payment_create_view, name='billing-create-payment'),
    path('bootstrap/', TemplateView.as_view(template_name='bootstrap/bootstrap.html'), name='bootstrap'),
    path('cart/', include(("carts.urls", "carts"), namespace='carts')),
	path('contact/', contact_page, name='contact'),
    path('history/products/', UserProductHistoryView.as_view(), name='user-product-history'),
	path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('orders/', include(("orders.urls", "orders"), namespace='orders')),
    path('products/', include(("products.urls", "products"), namespace='products')),
	path('register/', RegisterView.as_view(), name='register'),
    path('register/guest/', guest_register_view, name='guest_register'),
    path('settings/', RedirectView.as_view(url='/account')),
    path('settings/email/', MarketingPreferenceUpdateView.as_view(), name='marketing-preferences'),
    path('shipping/address/create', shipping_address_create, name='address_checkout'),
    path('shipping/address/reuse', shipping_address_reuse, name='address_reuse'),
    path('search/', include(("search.urls", "search"), namespace='search')),
    # path('products_fbv/', include('products.urls')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/models.py
from decimal import Decimal
from django.db import models
from django.conf import settings
from django.db.models.signals import *

from products.models import Product

User = settings.AUTH_USER_MODEL

class CartManger(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = Cart.objects.filter(id=cart_id)
        if qs.count() == 1:
            new_ob = False
            cart_obj = qs.first()
            if cart_obj.user is None and request.user.is_authenticated:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            new_ob = True
            cart_obj = Cart.objects.new(user=request.user)
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_ob

    def new(self, user=None):
        usr_obj=None
        if user is not None:
            if user.is_authenticated:
                usr_obj=user
        return Cart.objects.create(user=usr_obj)

class Cart(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    product = models.ManyToManyField(Product, blank=True)
    sub_total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    objects = CartManger()

    def __str__(self):
        return str(self.id)


def m2m_change_cart_receiver(sender, instance, action, *args, **kwargs):
    if action in ('post_add', 'post_remove', 'post_clear'):
        products = instance.product.all()
        total=0
        for p in products:
            total+=p.price
        instance.sub_total = total
        instance.save()

m2m_changed.connect(m2m_change_cart_receiver, sender=Cart.product.through)

def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.sub_total > 0:
        instance.total = float(Decimal(instance.sub_total) * Decimal(1.08))
    else:
        instance.total = 0.00

pre_save.connect(pre_save_cart_receiver, sender=Cart)

carts/views.py
from django.conf import settings
from django.shortcuts import render, redirect
from django.http import JsonResponse
from accounts.forms import LoginForm, GuestForm
from addresses.forms import AddressForm
from addresses.models import Address
from billing.models import BillingProfile
from products.models import Product
from .models import Cart
from orders.models import Order
# Create your views here.

import stripe
STRIPE_API_KEY = getattr(settings, 'STRIPE_API_KEY', "sk_test_FwYKvVTXyREQocEco8DvpMHl")
STRIPE_PUB_KEY = getattr(settings, 'STRIPE_PUB_KEY', "pk_test_8NgjOc0Ixb2zwKjJeAq1LBn7")

def cart_detais_api_view(request):
	cart_obj, new_obj = Cart.objects.new_or_get(request)
	products = [{
				'id':obj.id,
				'name':obj.title,
				'price':obj.price,
				'url':obj.get_absolute_url(),
				}
				 for obj in cart_obj.product.all()]
	cart_data = {'products':products, 'sub_total':cart_obj.sub_total, 'total':cart_obj.total}
	print(cart_data)
	return JsonResponse(cart_data)

def cart_home(request):
	cart_obj, new_obj = Cart.objects.new_or_get(request)
	return render(request, "carts/cart_home.html", context={'cart':cart_obj})

def cart_update(request):
	product_id = request.POST.get('product_id')
	print(product_id)
	if product_id is not None:
		try:
			product_obj = Product.objects.get(id=product_id)
		except Product.DoesNotExist:
			raise("Product Not Found")
			return redirect("carts:home")
		cart_obj, new_obj = Cart.objects.new_or_get(request)
		if product_obj in cart_obj.product.all():
			cart_obj.product.remove(product_obj)
			added = False
		else:
			cart_obj.product.add(product_obj)
			added = True
		request.session['cart_items'] = cart_obj.product.count()
		if request.is_ajax():
			json_data = {
				'added' : added,
				'removed' : not added,
				'cart_count' : cart_obj.product.count(),
			}
			return JsonResponse(json_data)
	return redirect("carts:home")

def cart_checkout(request):
	cart_obj , cart_created = Cart.objects.new_or_get(request)
	order_obj = None
	if cart_created or cart_obj.product.count() == 0:
		return redirect("carts:home")

	login_form = LoginForm()
	guest_form = GuestForm()

	billing_profile, billing_created = BillingProfile.objects.new_or_get(request)
	billing_address_id = request.session.get('billing_address_id', None)
	shipping_address_id = request.session.get('shipping_address_id', None)
	address_qs=None
	has_card = False
	if billing_profile is not None:
		if request.user.is_authenticated:
			address_qs = Address.objects.filter(billing_profile=billing_profile)
		order_obj, order_created = Order.objects.new_or_get(billing_profile, cart_obj)
		if shipping_address_id:
			order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
			del request.session['shipping_address_id']
		if billing_address_id:
			order_obj.billing_address = Address.objects.get(id=billing_address_id)
			del request.session['billing_address_id']
		if shipping_address_id or billing_address_id:
			order_obj.save()
		has_card = billing_profile.has_card

	if request.method == 'POST':
		is_done = order_obj.check_done()
		if is_done:
			charged, charge_msg = billing_profile.charge(order_obj)
			if charged:
				order_obj.mark_paid()
				request.session['cart_items'] = 0
				del request.session['cart_id']
				if not billing_profile.user:
					billing_profile.set_cards_inactive()
				return redirect('carts:success')
			else:
				return redirect('carts:checkout')

	address_form = AddressForm()
	context = {
		'billing_profile' : billing_profile,
		'object' : order_obj,
		'login_form' : login_form,
		'guest_form' : guest_form,
		'address_form' : address_form,
		'address_qs': address_qs,
		'has_card' : has_card,
		'pub_key' : STRIPE_PUB_KEY,
		'next_url' : request.build_absolute_uri
		}
	if order_obj:
		if not has_card and order_obj.billing_address and order_obj.shipping_address:
			return redirect("billing-payment")
	return render(request, "carts/checkout.html", context)

def checkout_success(request):
	return render(request, "carts/checkout_success.html", {})

carts/templates/carts/cart_home.html
{% extends "base.html" %}

{% block content%}

{% if cart.product.exists %}
<table class="table cart-table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Product Name</th>
      <th scope="col">Product Price</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody class="cart-body">
  	{% for obj in cart.product.all %}
	    <tr class="cart-products">
	      <th scope="row">{{forloop.counter}}</th>
	      <td><a href="{{obj.get_absolute_url}}">{{obj.title}}</a></td>
	      <td>{{obj.price}}</td>
	      <td>{% include "carts/cart_remove_item.html" with product_id=obj.id %}</td>
	    </tr>
	{% endfor %}
	    <tr>
	      <td colspan="2"></td>
	      <td><b>Sub Total</b> <span class="cart-sub-total">{{cart.sub_total}}</span></td>
	      <td></td>
	    </tr>
	    <tr>
	      <td colspan="2"></td>
	      <td><b>Total</b> <span class="cart-total">{{cart.total}}</span></td>
	      <td></td>
	    </tr>
	    <tr>
	      <td colspan="2"></td>
	      <td>
	      	<a class='btn btn-lg btn-success' href='{% url "carts:checkout" %}'>Checkout</a>
	      </td>
	      <td></td>
	    </tr>
  </tbody>
</table>

<div class="cart-remove-form" style="display:none;">
	{% include "carts/cart_remove_item.html" %}
</div>

{% else %}
	<p>Cart is empty</p>
{% endif %}
{% endblock%}

carts/templates/carts/cart_remove_item.html
<form class="form-product-ajax form aaa" method="POST" action="{% url 'carts:update' %}" data-endpoint="{% url 'carts:update' %}"> {% csrf_token %}
	<input class="remove_button" type="hidden" name="product_id" value="{{product_id}}">
	<button type="submit" class="btn btn-link">remove</button>
</form>

carts/templates/carts/checkout.html
{% extends "base.html" %}

{% block content %}

{% if billing_profile %}
	{% if not object.shipping_address %}
		<div class='row'>
			<div class='col-10 col-md-6 mx-auto'>
				<p class='lead'>Shipping Address</p>
				<hr/>
				<div class='row'>
					<div class="col">
						{% url 'address_checkout' as address_checkout_url %}
						{% include "addresses/snippets/form.html" with form=address_form next_url=request.build_absolute_uri active_url=address_checkout_url address_type='shipping' %}
					</div>
					<div class="col">
						{% url 'address_reuse' as reuse_address_url %}
						{% include "addresses/snippets/pre_addresses.html" with address_qs=address_qs next_url=request.build_absolute_uri address_type='shipping' action_url=reuse_address_url %}
					</div>
				</div>
			</div>
		</div>
	{% elif not object.billing_address %}
		<div class='row'>
			<div class='col-10 col-md-6 mx-auto'>
				<p class='lead'>Billing Address</p>
				<hr/>
				<div class="row">
					<div class="col">
						{% url 'address_checkout' as address_checkout_url %}
						{% include "addresses/snippets/form.html" with form=address_form next_url=request.build_absolute_uri active_url=address_checkout_url address_type='billing' %}
					</div>
					<div class="col">
						{% url 'address_reuse' as reuse_address_url %}
						{% include "addresses/snippets/pre_addresses.html" with address_qs=address_qs next_url=request.build_absolute_uri address_type='billing' action_url=reuse_address_url %}
					</div>
				</div>
			</div>
		</div>
	{% else %}
		{% if not has_card %}
			<!-- {% include "billing/payment.html" with pub_key=pub_key next_url=request.build_absolute_uri %} -->
			<div class='stripe-payment-form' data-token={{pub_key}} data-next-url='{{request.build_absolute_uri}}' data-btn-title="Add Payment Method"></div>
		{% else %}
			<h1>Finalize Checkout</h1>
			<p>Cart Items: {% for obj in object.cart.product.all %}{{obj}}{% if not forloop.last %},{% endif %}{% endfor %}</p>
			<p>Shipping Address : {{object.shipping_address.get_address}}</p>
			<p>Billing Address : {{object.billing_address.get_address}}</p>
			<p>Cart Price :  {{object.cart.total}}</p>
			<p>Payment Method :  {{billing_profile.default_card}} (<a href="{{billing_profile.get_payment_method_url}}?next={{request.build_absolute_uri}}">Change</a>)</p>
			<p>Shipping Price : {{object.shipping_total}}</p>
			<p>Total Price : {{object.total}}</p>
			<form method='POST', action=''>{% csrf_token %}
				<button type='submit'>Checkout</button>
			</form>
		{% endif %}
	{% endif %}
{% else %}
	<div class='row text-center'>
		<div class='col-12 col-md-6'>
			<p class='lead'>Login</p>
			{% include "accounts/snippets/checkout_login_form.html" with form=login_form next_url=request.build_absolute_uri %}
		</div>
		<div class='col-12 col-md-6'>
			<p class='lead'>Continue as Guest</p>
			{% url 'guest_register' as guest_url %}
			{% include "accounts/snippets/checkout_login_form.html" with form=guest_form next_url=request.build_absolute_uri active_url=guest_url %}
		</div>
	</div>
{% endif %}
{% endblock%}

carts/templates/carts/checkout_success.html
{% extends "base.html"%}

{% block content %}

<div class="col-6 mx-auto py-5 text-center">
	<h1 class='display-1'>Thanks for your Order !!!</h1>
</div>

{% endblock %}