carts/urls.py
from django.contrib import admin
from django.urls import path

from .views import cart_home, cart_update, cart_checkout, checkout_success

urlpatterns = [
    path('', cart_home, name='home'),
    path('checkout/', cart_checkout, name='checkout'),
    path('checkout/success', checkout_success, name='success'),
    path('update/', cart_update, name='update'),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from django.views.generic import TemplateView, RedirectView

from accounts.views import LoginView, RegisterView, guest_register_view, AccountHomeView
from addresses.views import shipping_address_create, shipping_address_reuse
from billing.views import billing_payment_view, billing_payment_create_view
from carts.views import cart_home, cart_detais_api_view
from marketing.views import MarketingPreferenceUpdateView
from products.views import UserProductHistoryView
from .views import home_page, about_page, contact_page

urlpatterns = [
	path('', home_page, name='home'),
	path('about/', about_page, name='about'),
    path('account/', AccountHomeView.as_view(), name='accounts'),
    path('accounts/', RedirectView.as_view(url='/account')),
    path('accounts/', include("accounts.passwords.urls")),
    path('admin/', admin.site.urls),
    path('api/cart/', cart_detais_api_view, name='api_cart'),
    path('billing-payment/', billing_payment_view, name='billing-payment'),
    path('billing-payment/create/', billing_payment_create_view, name='billing-create-payment'),
    path('bootstrap/', TemplateView.as_view(template_name='bootstrap/bootstrap.html'), name='bootstrap'),
    path('cart/', include(("carts.urls", "carts"), namespace='carts')),
	path('contact/', contact_page, name='contact'),
    path('history/products/', UserProductHistoryView.as_view(), name='user-product-history'),
	path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('orders/', include(("orders.urls", "orders"), namespace='orders')),
    path('products/', include(("products.urls", "products"), namespace='products')),
	path('register/', RegisterView.as_view(), name='register'),
    path('register/guest/', guest_register_view, name='guest_register'),
    path('settings/', RedirectView.as_view(url='/account')),
    path('settings/email/', MarketingPreferenceUpdateView.as_view(), name='marketing-preferences'),
    path('shipping/address/create', shipping_address_create, name='address_checkout'),
    path('shipping/address/reuse', shipping_address_reuse, name='address_reuse'),
    path('search/', include(("search.urls", "search"), namespace='search')),
    # path('products_fbv/', include('products.urls')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/css.html
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">

<link rel="stylesheet" type="text/css" href="{% static 'css/stripe-custom.css' %}">

templates/base/forms.html
{% extends "base.html" %}

{% block content %}
<div class='col-12 col-md-6 mx-auto'>
{% if title %}<h1 class='my-3'>{{ title }}</h1>{% endif %}
<form method='POST' action='{% if action_url %}{{ action_url }}{% endif %}'> {% csrf_token %}
    {% if next_url %}
    <input type='hidden' name='next' value='{{ next_url }}' />
    {% endif %}
  {{ form.as_p }}
  <button type='submit' class='btn btn-default'>Save</button>
</form>
</div>
{% endblock %}

templates/base/js.html
{% load static %}

<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>

<script src="https://js.stripe.com/v3/"></script>

<script src='https://cdnjs.cloudflare.com/ajax/libs/jsrender/0.9.88/jsrender.min.js'></script>
{% include 'base/js_template.html' %}

<script type="text/javascript" src="{% static 'js/ecommerce.js' %}"></script>

<script type="text/javascript" src="{% static 'js/ecommerce.main.js' %}"></script>

<script type="text/javascript" src="{% static 'js/django.ajax.js' %}"></script>

templates/base/js_template.html
{% verbatim %}
<script id="stripeTemplate" type="text/x-jsrender">

<form class="payment-form" action="/charge" method="post" id="payment-form" data-token={{:pubKey}} data-next-url={{:nextUrl}}>
  <div class="form-row">
    <!-- <label for="card-element">
      Add Payment Method
    </label> -->
    <div id="card-element" class='form-control'>
      <!-- A Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display form errors. -->
    <div id="card-errors" role="alert"></div>
  </div>

  <button class='btn btn-primary my-3'>{{:addTitle}}</button>
</form>

</script>
{% endverbatim %}

templates/base/nav-bar.html
{% url 'accounts' as account_url %}
{% url 'carts:home' as cart_url %}
{% url 'contact' as contact_url %}
{% url 'home' as home_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'products:list' as product_url %}
{% url 'register' as register_url %}

<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-3">
  <div class='container'>
  <a class="navbar-brand" href="{% url 'home' %}">#GET-IT
    <img src="https://getbootstap.com/docs/4.0/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapseLinks" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  <div class="collapse navbar-collapse" id="navbarCollapseLinks">
    <ul class="navbar-nav">
      <li class="nav-item {% if request.path == home_url %} active {% endif %}">
        <a class="nav-link" href="{{home_url}}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == contact_url %} active {% endif %}">
        <a class="nav-link" href="{{contact_url}}">Content</a>
      </li>
      <li class="nav-item {% if request.path == product_url %} active {% endif %}">
        <a class="nav-link" href="{{product_url}}">Products</a>
      </li>
      {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item {% if request.path == account_url %}active{% endif %}" href="{{ account_url }}">Home</a>
          <a class="dropdown-item" href="">Billing</a>
          <a class="dropdown-item" href="">History</a>
          <a class='dropdown-item' href="">Library</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{{ logout_url }}">Logout</a>
        </div>
      </li>
      {% else %}
        <li class="nav-item {% if request.path == register_url %} active {% endif %}">
          <a class="nav-link" href="{{register_url}}">Register</a>
        </li>
        <li class="nav-item {% if request.path == login_url %} active {% endif %}">
          <a class="nav-link" href="{{login_url}}">Login</a>
        </li>
      {% endif %}
      <li class="nav-item {% if request.path == cart_url %} active {% endif %}">
          <a class="nav-link" href="{{cart_url}}">
            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
            <span class="cart-count-span">{{request.session.cart_items}}</span>
          </a>
            
          </a>
        </li>
    </ul>
  </div>
  {% include "search/snippets/search-form.html" %}
</div>
</nav>